/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnModuleIdLessonIdRouteImport } from './routes/learn.$moduleId.$lessonId'
import { Route as ApiPublicMentorRouteImport } from './routes/api/public/mentor'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnModuleIdLessonIdRoute = LearnModuleIdLessonIdRouteImport.update({
  id: '/learn/$moduleId/$lessonId',
  path: '/learn/$moduleId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMentorRoute = ApiPublicMentorRouteImport.update({
  id: '/api/public/mentor',
  path: '/api/public/mentor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/replay': typeof ReplayRoute
  '/simulator': typeof SimulatorRoute
  '/learn/': typeof LearnIndexRoute
  '/api/public/mentor': typeof ApiPublicMentorRoute
  '/learn/$moduleId/$lessonId': typeof LearnModuleIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/replay': typeof ReplayRoute
  '/simulator': typeof SimulatorRoute
  '/learn': typeof LearnIndexRoute
  '/api/public/mentor': typeof ApiPublicMentorRoute
  '/learn/$moduleId/$lessonId': typeof LearnModuleIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/books': typeof BooksRoute
  '/journal': typeof JournalRoute
  '/onboarding': typeof OnboardingRoute
  '/quiz': typeof QuizRoute
  '/replay': typeof ReplayRoute
  '/simulator': typeof SimulatorRoute
  '/learn/': typeof LearnIndexRoute
  '/api/public/mentor': typeof ApiPublicMentorRoute
  '/learn/$moduleId/$lessonId': typeof LearnModuleIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/books'
    | '/journal'
    | '/onboarding'
    | '/quiz'
    | '/replay'
    | '/simulator'
    | '/learn/'
    | '/api/public/mentor'
    | '/learn/$moduleId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/books'
    | '/journal'
    | '/onboarding'
    | '/quiz'
    | '/replay'
    | '/simulator'
    | '/learn'
    | '/api/public/mentor'
    | '/learn/$moduleId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/books'
    | '/journal'
    | '/onboarding'
    | '/quiz'
    | '/replay'
    | '/simulator'
    | '/learn/'
    | '/api/public/mentor'
    | '/learn/$moduleId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BooksRoute: typeof BooksRoute
  JournalRoute: typeof JournalRoute
  OnboardingRoute: typeof OnboardingRoute
  QuizRoute: typeof QuizRoute
  ReplayRoute: typeof ReplayRoute
  SimulatorRoute: typeof SimulatorRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ApiPublicMentorRoute: typeof ApiPublicMentorRoute
  LearnModuleIdLessonIdRoute: typeof LearnModuleIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$moduleId/$lessonId': {
      id: '/learn/$moduleId/$lessonId'
      path: '/learn/$moduleId/$lessonId'
      fullPath: '/learn/$moduleId/$lessonId'
      preLoaderRoute: typeof LearnModuleIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mentor': {
      id: '/api/public/mentor'
      path: '/api/public/mentor'
      fullPath: '/api/public/mentor'
      preLoaderRoute: typeof ApiPublicMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BooksRoute: BooksRoute,
  JournalRoute: JournalRoute,
  OnboardingRoute: OnboardingRoute,
  QuizRoute: QuizRoute,
  ReplayRoute: ReplayRoute,
  SimulatorRoute: SimulatorRoute,
  LearnIndexRoute: LearnIndexRoute,
  ApiPublicMentorRoute: ApiPublicMentorRoute,
  LearnModuleIdLessonIdRoute: LearnModuleIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
